--- #YAML:1.0
name:                Net-SMTP-TLS-ButMaintained
version:             0.13_01
abstract:            An SMTP client supporting TLS and AUTH
license:             ~
author:              
    - Alexander Christian Westholm <awestholm@verizon.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Digest::HMAC_MD5:              0
    IO::Socket::INET:              0
    IO::Socket::SSL:               0
    MIME::Base64:                  0
    Net::SSLeay:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
